### ISSUE TITLE
[BUG] LSF log parsing - invalid wait_time & Host count

### ISSUE THREAD

**Issue by eranbrown** [aws-samples/hpc-cost-simulator#16]
**Describe the bug**
Parsing some records produces incorrect date and host count, preventing JobAnalyzer from processing the file.

Source record:
```
"JOB_FINISH" "10.1" 1656326065 908631 11046 33816602 1 1656326059 0 0 0 "OBFUSCATED" "OBFUSCATED" "rusage[Virtuoso_Multi_mode_Simulation=2:duration=1m] span[hosts=1]" "" "" "OBFUSCATED" "OBFUSCATED" "/dev/null" "/dev/null" "" "1656326059.908631" 0 0 32 1.0 "" "OBFUSCATED" -1.000000 -1.000000 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 "" "OBFUSCATED" 0 1 "" "" 0 0 0 "" "" "" "" 0 "" 14 "" -1 "" "OBFUSCATED" "" "" -1 "" "" 2097168 "" 0 "" "" 2 1032 "0" 1033 "0" 0 -1 64 0 "" "" -1 "" -1 0 "" 0 0 "" 0 "/tmp" 0 "" 0.000000 0.00 0.00 0.00 0.00 0 -1 0 0 0
```

Generates the following jobs.csv values:

|job_id|num_cores|max_mem_gb|num_hosts|submit_time|start_time|finish_time|resource_request|ineligible_pend_time|eligible_time|requeue_time|wait_time|run_time|exit_status|ru_inblock|ru_majflt|ru_maxrss|ru_minflt|ru_msgrcv|ru_msgsnd|ru_nswap|ru_oublock|ru_stime|ru_utime|
|------|---------|----------|---------|-------------------|-------------------|-------------------|----------------|--------------------|-------------------|------------|-----------------------|--------|-----------|----------|---------|---------|---------|---------|---------|--------|----------|--------|--------|
|908631|1|1|0|2022-06-27T10:34:19|1970-01-01T00:00:00|2022-06-27T10:34:25||0|2022-06-27T10:34:19|0|-19170--1 day, 13:25:41|0|0|-1|-1|-1|-1|-1|-1|-1|-1|||

**Expected behavior**
1. Non zero host count
2. Correct time format for wait_time

**Repository Version**
Repository cloned on 2022-06-28

**Comment by cartalla** [comment]
The job never started. The StartTime is 0 so the job should be ignored. The WaitTime can't be determined because the job never ran.

The fix for #18 added a check for this:

```
            if record['startTime'] == 0 and record['runTime'] == 0:
                continue
```

I've added a debug message saying that the job is ignored.
