### ISSUE TITLE
[BUG] Excel file opens with formula update disabled on Mac

### ISSUE THREAD

**Issue by eranbrown** [aws-samples/hpc-cost-simulator#51]
**Describe the bug**
When opening the Excel on Excel for Mac, any change of a field requires the user to manually force every formula that depends on this field to re-calculate.
This is because the "formula update" option (formulas --> Calculation options) is set to "Manual" and not "Automatic".

**To Reproduce**
1. On mac, open the Excel file
2. Try to change the first instance type's ESP commitment
3. the "Total" field doesn't change

**Expected behavior**
Sheet should had "Calculate Options" set to "Automatic" when HCS creates it.

**Repository Version**
[59840dc](https://github.com/aws-samples/hpc-cost-simulator/commit/59840dcd308c241ec91c1e2d4757ca21a2da99a6)

**Comment by cartalla** [comment]
Eran, I don't have any way to verify this because it works on Windows Excel on Linux LibreOffice.

I've created a PR with a potential change, but I need you to try it out.
